### ISSUE TITLE
rand.c WIN32 code path

### ISSUE THREAD

**Issue by kmar** [trezor/trezor-crypto#94]
I've noticed that you use srand(time(NULL)) before each random32,
this is not a good idea as time() it has a granularity of 1 second (!!!!) so it's very likely
that a sequence of random32 calls generates the same pseudo-random numbers...
Also, using rand() on Windows means naive LCG.
This very unsafe IMHO.

I'm wondering - why not replace it with CryptoAPI's CryptGenRandom?

**Comment by prusnak** [comment]
WIN32 support in trezor-crypto is not a first-class citizen, because the library is meant to be used on embedded microcontrollers such as ARM Cortex-M4. 

I am not sure anymore why we added WIN32 support to the library, probably to satisfy some unit tests, but I would not recommend anyone using this library under Windows.

That said, feel free to send a pull request with Win32 fixes if you care about this use case.
